### ISSUE TITLE
Unable to access WaitUntil 

### ISSUE THREAD

**Issue by AdzeB** [upstash/workflow-js#7] opened 2024-10-23 13:06 UTC
Hi, I am interested in using the new wait-until feature. I am on the latest version but I can't access it

Please have the screenshots below of the code and my package.json...I have tried with both npm and bun as package managers

Package.json:
<img width="658" alt="image" src="https://github.com/user-attachments/assets/34e48eef-7356-4f33-9e65-9abe32cedc98">

Code:
<img width="892" alt="image" src="https://github.com/user-attachments/assets/49985728-967b-40fa-983c-64025d0fafb6">

**Comment by CahidArda** [comment] 2024-10-24 09:22
hi there,

How do you import the `serve` method? You should import from `@upstash/workflow`, not `@upstash/qstash`:

[See our migration guide for more details](https://upstash.com/docs/workflow/migration).

**Comment by AdzeB** [comment] 2024-11-09 10:11
@CahidArda Thanks it worked, I forgot to reply.

**Comment by CahidArda** [comment] 2024-11-09 21:37
I am glad that the issue is sorted out. Closing this issue.

**Closed by CahidArda** 2024-11-09 21:37 UTC
